version: "2"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  flask:
    build:
      context: .
    command: sh -c "alembic upgrade head && python -m flask --app app.main run --host=0.0.0.0 --port=5000 --reload --debug"
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    restart: always
