"""create table of registration

Revision ID: 4083b196fbe7
Revises: 2c51b7aa86db
Create Date: 2024-03-19 13:54:58.937314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4083b196fbe7'
down_revision: Union[str, None] = '2c51b7aa86db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank', sa.String(length=100), nullable=False),
    sa.Column('bik', sa.Integer(), nullable=False),
    sa.Column('rs', sa.Integer(), nullable=False),
    sa.Column('ks', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bik'),
    sa.UniqueConstraint('ks'),
    sa.UniqueConstraint('rs')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requisites')
    # ### end Alembic commands ###
