"""add

Revision ID: 84ef8065c331
Revises: 4083b196fbe7
Create Date: 2024-03-19 15:12:43.890286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84ef8065c331'
down_revision: Union[str, None] = '4083b196fbe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requisites', sa.Column('activity', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requisites', 'activity')
    # ### end Alembic commands ###
