"""add_swift_and_iban

Revision ID: f0d564e0c97a
Revises: 5687e923e456
Create Date: 2024-03-22 19:49:27.554738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0d564e0c97a'
down_revision: Union[str, None] = '5687e923e456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requisites', sa.Column('swift', sa.String(length=35), nullable=False))
    op.add_column('requisites', sa.Column('iban', sa.String(length=11), nullable=True))
    op.create_unique_constraint(None, 'requisites', ['swift'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requisites', type_='unique')
    op.drop_column('requisites', 'iban')
    op.drop_column('requisites', 'swift')
    # ### end Alembic commands ###
